# Generated by Django 2.2.4 on 2020-06-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0002_auto_20200604_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvals',
            name='applicant_income',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='approvals',
            name='co_applicant_income',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='approvals',
            name='credit_history',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='approvals',
            name='dependents',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='approvals',
            name='loan_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='approvals',
            name='loan_amount_term',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
