# Generated by Django 2.2.4 on 2020-06-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_about_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentwork',
            name='title_id',
            field=models.CharField(default='loan', max_length=100, verbose_name='Work title linked to url name'),
            preserve_default=False,
        ),
    ]
