# Generated by Django 2.2.4 on 2020-06-04 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0004_auto_20200604_1846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approvals',
            old_name='applicant_income',
            new_name='ApplicantIncome',
        ),
        migrations.RenameField(
            model_name='approvals',
            old_name='co_applicant_income',
            new_name='CoapplicantIncome',
        ),
        migrations.RenameField(
            model_name='approvals',
            old_name='credit_history',
            new_name='Credit_History',
        ),
        migrations.RenameField(
            model_name='approvals',
            old_name='dependants',
            new_name='Dependents',
        ),
        migrations.RenameField(
            model_name='approvals',
            old_name='education',
            new_name='Education',
        ),
        migrations.RenameField(
            model_name='approvals',
            old_name='firstname',
            new_name='Firstname',
        ),
        migrations.RenameField(
            model_name='approvals',
            old_name='gender',
            new_name='Gender',
        ),
        migrations.RenameField(
            model_name='approvals',
            old_name='lastname',
            new_name='Lastname',
        ),
        migrations.RenameField(
            model_name='approvals',
            old_name='loan_amount',
            new_name='LoanAmount',
        ),
        migrations.RenameField(
            model_name='approvals',
            old_name='loan_amount_term',
            new_name='Loan_Amount_Term',
        ),
        migrations.RenameField(
            model_name='approvals',
            old_name='married',
            new_name='Married',
        ),
        migrations.RenameField(
            model_name='approvals',
            old_name='property_area',
            new_name='Property_Area',
        ),
        migrations.RenameField(
            model_name='approvals',
            old_name='self_employed',
            new_name='Self_Employed',
        ),
    ]
